export {default as HeroContent} from './hero/hero-content'
export {default as InnerCard} from './card/inner-card'
export {default as Rating} from './slider/rating'
export {default as MovieSlider} from './slider/slider'
export {default as Selector} from './header/select'
export {default as HMenu} from './header/h-menu'
export {default as Loade} from './slider/loading'
export {default as AuthCard} from './login/signUp'
