import { NewData } from "@/types/props";

export const localMovies: NewData[] = [
  // 10 General Movies
  { id: "1", title: "Inception", poster_url: "https://image.tmdb.org/t/p/original/8Z8dptEqENbqGfHsq0nWA2A1o0K.jpg", description: "A thief enters the dreams of others to steal secrets.", year: 2010, rating: 8.8, genres: "Action, Sci-Fi", time: 148 },
  { id: "2", title: "The Dark Knight", poster_url: "https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg", description: "Batman faces the Joker in Gotham City.", year: 2008, rating: 9.0, genres: "Action, Crime", time: 152 },
  { id: "3", title: "Interstellar", poster_url: "https://image.tmdb.org/t/p/original/gEU2QlsEOWepVNzMU5cR8ZqOktZ.jpg", description: "Astronauts travel through a wormhole in search of a new home.", year: 2014, rating: 8.6, genres: "Adventure, Sci-Fi", time: 169 },
  { id: "4", title: "Parasite", poster_url: "https://image.tmdb.org/t/p/original/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", description: "A poor family schemes to become employed by a wealthy family.", year: 2019, rating: 8.5, genres: "Thriller, Drama", time: 132 },
  { id: "5", title: "The Matrix", poster_url: "https://image.tmdb.org/t/p/original/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg", description: "A computer hacker learns the true nature of reality.", year: 1999, rating: 8.7, genres: "Action, Sci-Fi", time: 136 },
  { id: "6", title: "Gladiator", poster_url: "https://image.tmdb.org/t/p/original/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg", description: "A betrayed Roman general seeks revenge.", year: 2000, rating: 8.5, genres: "Action, Drama", time: 155 },
  { id: "7", title: "Pulp Fiction", poster_url: "https://image.tmdb.org/t/p/original/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg", description: "The lives of two mob hitmen, a boxer, and a pair of diner bandits intertwine.", year: 1994, rating: 8.9, genres: "Crime, Drama", time: 154 },
  { id: "8", title: "Forrest Gump", poster_url: "https://image.tmdb.org/t/p/original/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg", description: "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75.", year: 1994, rating: 8.8, genres: "Drama, Romance", time: 142 },
  { id: "9", title: "The Shawshank Redemption", poster_url: "https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg", description: "Two imprisoned men bond over a number of years.", year: 1994, rating: 9.3, genres: "Drama", time: 142 },
  { id: "10", title: "The Godfather", poster_url: "https://image.tmdb.org/t/p/original/3bhkrj58Vtu7enYsRolD1fZdja1.jpg", description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.", year: 1972, rating: 9.2, genres: "Crime, Drama", time: 175 },

  // 10 Anime Movies
  { id: "11", title: "Spirited Away", poster_url: "https://image.tmdb.org/t/p/original/39wmItIWsg5sZMyRUHLkBg8lWOb.jpg", description: "A young girl wanders into a world ruled by gods, witches, and spirits.", year: 2001, rating: 8.6, genres: "Anime, Fantasy", time: 125 },
  { id: "12", title: "Your Name", poster_url: "https://image.tmdb.org/t/p/original/q719jXXEzOoYaps6babgKnONONX.jpg", description: "Two strangers find themselves linked in a bizarre way.", year: 2016, rating: 8.4, genres: "Anime, Romance", time: 106 },
  { id: "13", title: "Princess Mononoke", poster_url: "https://image.tmdb.org/t/p/original/jHWmNr7m544fJ8eFfhd0A1Zq6hS.jpg", description: "A prince becomes involved in the struggle between a forest princess and the encroachment of mechanization.", year: 1997, rating: 8.4, genres: "Anime, Fantasy", time: 134 },
  { id: "14", title: "Akira", poster_url: "https://image.tmdb.org/t/p/original/bKzK6rD2P3sA8D497gS1O090V28.jpg", description: "A secret military project endangers Neo-Tokyo when it turns a biker gang member into a rampaging psychic psychopath.", year: 1988, rating: 8.0, genres: "Anime, Sci-Fi", time: 124 },
  { id: "15", title: "Grave of the Fireflies", poster_url: "https://image.tmdb.org/t/p/original/qG3RYlIVpTYclR9c8zlqXUNT81n.jpg", description: "A young boy and his little sister struggle to survive in Japan during World War II.", year: 1988, rating: 8.5, genres: "Anime, Drama", time: 89 },
  { id: "16", title: "Howl's Moving Castle", poster_url: "https://image.tmdb.org/t/p/original/TlquqEqDqD1jFw1Bssq02mnd2y.jpg", description: "When an unconfident young woman is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard.", year: 2004, rating: 8.2, genres: "Anime, Fantasy", time: 119 },
  { id: "17", title: "Perfect Blue", poster_url: "https://image.tmdb.org/t/p/original/a0sEd0fB3iL5Nf4I4O1L61w4yvM.jpg", description: "A pop singer gives up her career to become an actress, but she slowly goes mad when she starts being stalked by an obsessed fan.", year: 1997, rating: 8.0, genres: "Anime, Thriller", time: 81 },
  { id: "18", title: "Weathering with You", poster_url: "https://image.tmdb.org/t/p/original/qgrk7r1fV4IjuoeiGS5HOZNdPeO.jpg", description: "A high-school boy who has run away to Tokyo befriends a girl who appears to be able to manipulate the weather.", year: 2019, rating: 7.5, genres: "Anime, Romance", time: 112 },
  { id: "19", title: "My Neighbor Totoro", poster_url: "https://image.tmdb.org/t/p/original/rtGDOeG9LzoerkLSNvSRMNVdSVf.jpg", description: "Two girls move to the country to be near their ailing mother and have adventures with the wondrous forest spirits who live nearby.", year: 1988, rating: 8.1, genres: "Anime, Fantasy", time: 86 },
  { id: "20", title: "A Silent Voice", poster_url: "https://image.tmdb.org/t/p/original/drnB1EIfHjT9x1bIARe2FpT1OQn.jpg", description: "A young man is ostracized after he bullies a deaf girl.", year: 2016, rating: 8.1, genres: "Anime, Drama", time: 130 },

  // 10 Fantasy Movies
  { id: "21", title: "The Lord of the Rings: The Fellowship of the Ring", poster_url: "https://image.tmdb.org/t/p/original/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg", description: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring.", year: 2001, rating: 8.8, genres: "Fantasy, Adventure", time: 178 },
  { id: "22", title: "Harry Potter and the Sorcerer's Stone", poster_url: "https://image.tmdb.org/t/p/original/wuMc08FTl903s8TfDkYkE6kofjA.jpg", description: "An orphaned boy enrolls in a school of wizardry.", year: 2001, rating: 7.6, genres: "Fantasy, Family", time: 152 },
  { id: "23", title: "Pan's Labyrinth", poster_url: "https://image.tmdb.org/t/p/original/pF7x1n49x2w1kH1c36u0P6L0O6T.jpg", description: "In the Falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.", year: 2006, rating: 8.2, genres: "Fantasy, Drama", time: 118 },
  { id: "24", title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe", poster_url: "https://image.tmdb.org/t/p/original/iREd0r818D26c4N9sHh0T2U0C8j.jpg", description: "Four kids travel through a wardrobe to the land of Narnia.", year: 2005, rating: 6.9, genres: "Fantasy, Adventure", time: 143 },
  { id: "25", title: "Stardust", poster_url: "https://image.tmdb.org/t/p/original/oX2Z77w0sEebLqQjZ8FpM05LtoP.jpg", description: "In a countryside town bordering on a magical land, a young man makes a promise to his beloved that he'll retrieve a fallen star.", year: 2007, rating: 7.6, genres: "Fantasy, Romance", time: 127 },
  { id: "26", title: "Alice in Wonderland", poster_url: "https://image.tmdb.org/t/p/original/Ah3yJc3rLz1Z2T7F1jJz9L9X8.jpg", description: "19-year-old Alice returns to the magical world from her childhood adventure.", year: 2010, rating: 6.4, genres: "Fantasy, Family", time: 108 },
  { id: "27", title: "Labyrinth", poster_url: "https://image.tmdb.org/t/p/original/iGZ6vT1RjR8q4eSDBP1C6V36CJi.jpg", description: "A 16-year-old girl is given 13 hours to solve a labyrinth and rescue her baby brother.", year: 1986, rating: 7.3, genres: "Fantasy, Family", time: 101 },
  { id: "28", title: "The Dark Crystal", poster_url: "https://image.tmdb.org/t/p/original/2wT8n8bZkC3tQy6pE13Y5Z5J5zF.jpg", description: "On another planet in the distant past, a Gelfling embarks on a quest to find the missing shard of a magical crystal.", year: 1982, rating: 7.1, genres: "Fantasy, Adventure", time: 93 },
  { id: "29", title: "Clash of the Titans", poster_url: "https://image.tmdb.org/t/p/original/wzM3i1f40l9vKkT2Z826oQO6hN4.jpg", description: "Perseus must battle Medusa and the Kraken to save the Princess Andromeda.", year: 1981, rating: 6.9, genres: "Fantasy, Action", time: 118 },
  { id: "30", title: "Willy Wonka & the Chocolate Factory", poster_url: "https://image.tmdb.org/t/p/original/2wT8n8bZkC3tQy6pE13Y5Z5J5zF.jpg", description: "A poor but hopeful boy seeks one of the five coveted golden tickets that will send him on a tour of Willy Wonka's mysterious chocolate factory.", year: 1971, rating: 7.8, genres: "Fantasy, Family", time: 100 }
];
